In [1]:
import numpy as np
np.__version__

'1.23.5'

In [2]:
arr=np.array([1,2,3,4,5,6],dtype="float")
print(arr)
print(type(arr))

[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>


In [4]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.quantile(arr,0.25))
print(np.quantile(arr,0.33))

[1 2 3 4 5 6]
21
3.5
3.5
1
6
2.25
2.6500000000000004


In [11]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr[2],[0])

[7 8 9] [0]


In [5]:
import numpy as np
arr=np.zeros([2,4],dtype="int")
print(arr)

[[0 0 0 0]
 [0 0 0 0]]


In [6]:
import numpy as np
arr=np.ones([2,4],dtype="int")
print(arr)

[[1 1 1 1]
 [1 1 1 1]]


In [7]:
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
c=np.zeros_like(arr)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
import numpy as np
np.random.randn(3,4)

array([[ 1.19358407,  1.7882224 , -0.6399036 , -0.51954258],
       [ 0.91069406,  0.17247026, -1.86345206,  1.00503722],
       [-0.15020381,  1.26154594, -0.31432244, -0.83269878]])

In [9]:
import numpy as np
np.random.randn(4,4)

array([[-0.17433636,  0.34059437, -0.18239949,  0.21721964],
       [ 0.15675063,  0.78380458,  0.40120467, -0.34222633],
       [ 1.15894612, -1.92207178, -0.95859247,  0.09199564],
       [ 0.0182164 , -0.27535903, -0.53431827, -1.29047993]])

In [13]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
import numpy as np
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
import numpy as np
arr=np.arange(12).reshape(6,2)
print(arr)
print(arr.shape)
print(np.ndim(arr))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(6, 2)
2


In [18]:
import numpy as np
arr=np.arange(9).reshape(3,3)
print(type(arr))
print(arr)
print(arr.shape)
print(np.ndim(arr))

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
2


In [19]:
print(arr[0])

[0 1 2]


In [20]:
print(arr[0][1])

1


In [21]:
import numpy as np
arr1=np.arange(15).reshape(5,3)
arr2=np.random.randn(5,1)
print(arr1+arr2)

[[ 1.60815674  2.60815674  3.60815674]
 [ 2.54125277  3.54125277  4.54125277]
 [ 5.76295887  6.76295887  7.76295887]
 [ 7.45156935  8.45156935  9.45156935]
 [11.58827494 12.58827494 13.58827494]]


In [22]:
import numpy as np
arr1=np.arange(15).reshape(5,3)
arr2=np.arange(5).reshape(5,1)
print(arr1+arr2)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


# Matrix multiplication

import numpy as np
arr1=np.arange(4).reshape(2,2)
arr2=np.random.randn(2,2)
arr1.dot(arr2)

# Simultaneous equation

In [28]:
a=np.array([[7,5,-3],[3,-5,2],[5,3,-7]])
b=np.array([60,-8,0])
np.linalg.solve(a,b)

array([5.984375, 8.328125, 7.84375 ])

In [29]:
import numpy as np
arr=np.array([[1,2],[3,4]])
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
import numpy as np
arr=np.array([[1,2],[3,4]])
np.linalg.det(arr)

-2.0000000000000004